---
name: Pre-changelog

on: [push]

jobs:
  changelog:
    name: Show pre-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - name: Show pre-changelog
        run: |
          npm install
          echo "[release version]"
          echo >>$GITHUB_ENV VERSION=$(npx standard-version --dry-run | grep tagging | cut -d ' ' -f4)

          echo "[description]"
          DESCRIPTION=$(npx standard-version --dry-run --silent | grep -v Done | grep -v "\-\-\-" | grep -v standard-version)
          DESCRIPTION="${DESCRIPTION//'%'/%}"
          DESCRIPTION="${DESCRIPTION//$'\n'/\\n}"
          DESCRIPTION="${DESCRIPTION//$'\r'/\\n}"
          echo >>$GITHUB_ENV DESCRIPTION=$DESCRIPTION
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              text: 'Release ${{ env.VERSION }}',
              attachments: [
                {
                  "author_name": `${process.env.AS_AUTHOR}`,
                  fallback: 'fallback',
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  title: 'pre-changelog',
                  text: `${{ job.status }}`,
                  fields: [
                    {
                      title: '[Workflow]',
                      value: `${process.env.AS_WORKFLOW}`,
                      short: true
                    },
                    {
                      title: '[Repository]',
                      value: `${process.env.AS_REPO}`,
                      short: true
                    },
                    {
                      title: '[Version]',
                      value: '${{ env.VERSION }}',
                      short: false
                    },
                    {
                      title: '[Description]',
                      value: '${{ env.SLACK_DESCRIPTION }}',
                      short: false
                    }
                  ]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

