---
name: Pre-changelog

on: [push]

jobs:
  changelog:
    name: Show pre-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - name: Show pre-changelog
        run: |
          npm install
          VERSION=$(npx standard-version --dry-run | grep tagging | cut -d ' ' -f4)
          echo "[release version]"
          echo "::set-env name=VERSION::$VERSION"
          
          echo "[description]"
          DESCRIPTION=$(npx standard-version --dry-run --silent | grep -v Done | grep -v "\-\-\-" | grep -v standard-version)
          DESCRIPTION="${DESCRIPTION//'%'/%}"
          DESCRIPTION="${DESCRIPTION//$'\n'/\\n}"
          DESCRIPTION="${DESCRIPTION//$'\r'/\\n}"
          echo "::set-env name=DESCRIPTION::$DESCRIPTION"
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              attachments: [
                {
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: 'Github Actions',
                  fields: [
                    {
                      title: 'workflow',
                      value: '${process.env.AS_WORKFLOW}',
                      short: true
                    },
                    {
                      title: 'repo',
                      value: '${process.env.AS_REPO}'
                      short: true
                    },
                    {
                      title: 'author',
                      value: '${process.env.AS_AUTHOR}',
                      short: true
                    },
                    {
                      title: 'version',
                      value: '${{ env.VERSION }}',
                      short: false
                    },
                    {
                      title: 'description',
                      value: ' ${{ env.DESCRIPTION }}',
                      short: false
                    }
                  ]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
