---
name: Pre-changelog

on: [push]

jobs:
  changelog:
    name: Show pre-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - name: Show pre-changelog
        run: |
          npm install
          echo "[release version] $(npx standard-version --dry-run | grep tagging | cut -d ' ' -f4)"
          echo "[description]"
          DESCRIPTION=$(npx standard-version --dry-run --silent | grep -v Done | grep -v "\-\-\-" | grep -v standard-version)
          DESCRIPTION="${DESCRIPTION//'%'/'%25'}"
          DESCRIPTION="${DESCRIPTION//$'\n'/'%0A'}"
          DESCRIPTION="${DESCRIPTION//$'\r'/'%0D'}"
          echo "::set-env name=DESCRIPTION::$DESCRIPTION"
          echo "$DESCRIPTION"
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          job_name: release notification
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              username: 'github',
              attachments: [
                {
                  color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                  text: "${{ env.DESCRIPTION }}"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
