---
name: Pre-changelog

on: [push]

jobs:
  changelog:
    name: Show pre-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - name: Show pre-changelog
        run: |
          npm install
          echo "[release version]"
          echo >>$GITHUB_ENV VERSION=$(npx standard-version --dry-run | grep tagging | cut -d ' ' -f4)

          echo "[description]"
          DESCRIPTION=$(npx standard-version --dry-run --silent | grep -v Done | grep -v "\-\-\-" | grep -v standard-version)
          DESCRIPTION="${DESCRIPTION//'%'/%}"
          DESCRIPTION="${DESCRIPTION//$'\n'/\\n}"
          DESCRIPTION="${DESCRIPTION//$'\r'/\\n}"
          echo >>$GITHUB_ENV DESCRIPTION=$DESCRIPTION

